cookie:
  expiry_days: 1
  key: key
  name: name
credentials:
  usernames:
    admin:
      email: admin@admin.com
      failed_login_attempts: 0 
      first_name: admin
      last_name: admin
      logged_in: False 
      password: admin 